In [2]:
import torch
a = torch.randn((2,3,4))
a

tensor([[[ 0.0944, -0.8411, -0.8205,  0.5996],
         [ 0.1807, -2.0585,  1.7893, -0.4119],
         [ 1.0201, -0.5517, -0.1740,  0.1535]],

        [[ 0.2008,  0.3388, -0.9598, -0.4192],
         [ 1.1305, -0.2445, -0.9994,  1.0016],
         [ 0.6535,  0.3173,  0.0923,  0.8765]]])

In [8]:
(a>1).nonzero()

tensor([[0, 1, 2],
        [0, 2, 0],
        [1, 1, 0],
        [1, 1, 3]])

In [17]:
a = torch.tensor([[0,0,0,0,0,1,0,0,0,0,],[0,0,0,0,0,1,0,0,0,0,],[0,0,0,0,0,1,0,0,0,0,]])
m = (a==1).nonzero()
m

tensor([[0, 5],
        [1, 5],
        [2, 5]])

In [ ]:
from torch.nn import functional as F

In [19]:
for i in m:
    print(i[-1])
    s = F.relu(i-16)
    e = i+16
    

tensor(5)
tensor(5)
tensor(5)
